In [121]:
import pandas as pd
import numpy as np

In [122]:
train=pd.read_csv("trainprocessed.csv")

In [123]:
train=train.rename(mapper={train.columns[0]:"first"},axis=1)

In [124]:
train.index=train.loc[:,'first']

In [125]:
train=train.drop(['first','Tweet'],axis=1)

In [126]:
train=train.astype(dtype=np.int)

In [127]:
trainy=train.Type

In [128]:
trainx=train.drop('Type',axis=1)

In [129]:
test=pd.read_csv("testprocessed.csv")

In [130]:
test=test.rename(mapper={test.columns[0]:"first"},axis=1)

In [131]:
test.index=test.loc[:,'first']

In [132]:
test=test.drop(['first','Tweet'],axis=1)

In [133]:
test.astype(dtype=np.int)

WEBSITE_ADDRESS_HERE  com  I  thi  ...  Trump  …  RT  like  wa  ...  \
first                                                                  ...   
6243                      0    0  0    0    0      0  0   0     0   0  ...   
1351                      1    0  0    0    0      0  0   0     0   0  ...   
10418                     0    0  0    0    0      0  0   0     0   0  ...   
3752                      1    0  0    0    0      0  0   0     0   0  ...   
304                       1    0  0    0    0      0  0   0     0   0  ...   
...                     ...  ... ..  ...  ...    ... ..  ..   ...  ..  ...   
4969                      1    0  1    0    0      0  0   0     0   0  ...   
5790                      0    0  0    0    0      0  0   0     0   0  ...   
563                       1    0  0    0    0      1  0   0     0   0  ...   
1722                      0    0  1    1    0      0  0   0     1   0  ...   
4747                      1    0  0    0    0      1  0   0     0   0  ...   

       Quack  District  cost  18  Free  Google  mix  tool  Aleppo  Type  
first                                                                    
6243       0         0     0   0     0       0    0     0       0     0  
1351       0         0     0   0     0       0    0     0       0     1  
10418      0         0     0   0     0       0    0     0       0     1  
3752       0         0     0   0     0       0    0     0       0     0  
304        0         0     0   0     0       0    0     0       0     0  
...      ...       ...   ...  ..   ...     ...  ...   ...     ...   ...  
4969       0         0     0   0     0       0    0     0       0     1  
5790       0         0     0   0     0       0    0     0       0     1  
563        0         0     0   0     0       0    0     0       0     0  
1722       0         0     0   0     0       0    0     0       0     1  
4747       0         0     0   0     0       0    0     0       0     0  

[1796 rows x 1001 columns]

In [134]:
testy=test.Type

In [135]:
testx=test.drop('Type',axis=1)

In [152]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [153]:
model=BernoulliNB()

In [154]:
model.fit(trainx,trainy)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [155]:
y_pred=model.predict(testx)

In [156]:
score=accuracy_score(testy,y_pred)

In [157]:
matrix=confusion_matrix(testy,y_pred)

In [158]:
score

0.6069042316258352

In [159]:
matrix

array([[509, 376],
       [330, 581]], dtype=int64)

In [169]:
from sklearn.tree import DecisionTreeClassifier

In [170]:
model2=DecisionTreeClassifier()

In [171]:
model2.fit(trainx,trainy)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [172]:
y_pred=model.predict(testx)

In [173]:
score=accuracy_score(testy,y_pred)

In [174]:
matrix=confusion_matrix(testy,y_pred)

In [175]:
score

0.5857461024498887

In [176]:
matrix

array([[500, 385],
       [359, 552]], dtype=int64)

In [197]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [198]:
final_estimator=LogisticRegression()

In [199]:
stack=StackingClassifier([("BernoulliNB",model),('DecisionTreeClassifier',model2)],final_estimator=final_estimator,cv=5,passthrough=False)

In [200]:
stack.fit(trainx,trainy)

StackingClassifier(cv=5,
                   estimators=[('BernoulliNB',
                                DecisionTreeClassifier(ccp_alpha=0.0,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features=None,
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       presort='deprecated',
               

In [201]:
y_pred=stack.predict(testx)

In [202]:
score=accuracy_score(testy,y_pred)

In [203]:
matrix=confusion_matrix(testy,y_pred)

In [204]:
score

0.5929844097995546

In [205]:
matrix

array([[504, 381],
       [350, 561]], dtype=int64)